apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: production-oscen
  source:
    path: packages/grafana
    repoURL: https://github.com/oscenbot/ops
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true