apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jaeger
    server: https://kubernetes.default.svc
  project: production-oscen
  source:
    path: packages/jaeger
    repoURL: https://github.com/oscenbot/ops
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true